export enum APIEnumTypes {
    PUNISHMENT = "punishment",
    VIEWPERMISSION = "viewpermission",
    AUTOMODACTION = "automodaction",
    AUTOMODTYPE = "automodtype",
    CASECREATIONTYPE = "casecreationtype",
    LANGUAGE = "language",
    APIERRORS = "apierror",
    AUTOMODCHANNELNOTIFICATIONBEHAVIOR = "automodchannelbehavior",
    EDITSTATUS = "editstatus",
    LOCKEDCOMMENTSTATUS = "lockedcommentstatus",
    MARKEDTODELETESTATUS = "markedtodeletestatus",
    PUNISHMENTACTIVESTATUS = "punishmentactivestatus",
    SCHEDULEMESSAGESTATUS = "scheduledmessagestatus",
    SCHEDULEMESSAGEFAILUREREASON = "scheduledmessagefailurereason",
}