namespace MASZ.Enums
{
    public enum TelemetryDataUsageActionType
    {
        UNKNOWN = 0,
        LOGIN = 1,
        LOGOUT = 2,
        MODCASE_CREATE = 3,
        MODCASE_UPDATE = 4,
        MODCASE_DELETE = 5,
        MODCASE_RESTORE = 6,
        MODCASE_CREATE_COMMENT = 7,
        MODCASE_UPDATE_COMMENT = 8,
        MODCASE_DELETE_COMMENT = 9,
        MODCASE_UPLOAD_ATTACHMENT = 10,
        MODCASE_DELETE_ATTACHMENT = 11,
        MODCASE_LINK_TO_MODCASE = 12,
        MODCASE_UNLINK_TO_MODCASE = 13,

        COMMENTS_LOCK = 14,
        COMMENTS_UNLOCK = 15,

        APPEAL_CREATE = 16,
        APPEAL_DENIED = 17,
        APPEAL_ACCEPTED = 18,
        APPEAL_CONFIGURED = 19,

        USERNOTE_CREATE = 20,
        USERNOTE_UPDATE = 21,
        USERNOTE_DELETE = 22,

        USERMAP_CREATE = 23,
        USERMAP_UPDATE = 24,
        USERMAP_DELETE = 25,

        SCHEDULED_MESSAGE_CREATE = 26,
        SCHEDULED_MESSAGE_UPDATE = 27,
        SCHEDULED_MESSAGE_DELETE = 28,

        MOTD_EDITED = 29,

        AUDITLOG_EDITED = 30,

        AUTOMOD_EDITED = 31,

        ZALGO_EDITED = 32,

        GUILD_ADDED = 33,
        GUILD_EDITED = 34,
        GUILD_REMOVED = 35,

        ADMIN_SETTINGS_EDITED = 36,

        APPLICATION_COMMAND_USED = 37,

        CASE_TEMPLATE_CREATE = 38,
    }
}